import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import FollowBar from "@/components/FollowBar";
import Modal from "@/components/Modal";
import { useEffect, useState } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps{
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({children}) => {
    const [isAuthenticated, setIsAuthenticated] = useState(false);
    // useEffect(() => {
    //   if 
    // })
return(
  <html lang="en">
    <body>

      {!isAuthenticated && <Modal isOpen title="Test Modal"/>}

      {isAuthenticated && 
       <div className="h-screen bg-black">
        <div className="container h-full mx-auto xl:px-30 max-w-6xl">
          <div className="grid grid-cols-4 h-full">
            
            <Sidebar/>
            
            <div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800">
                {children}
            </div>

            <FollowBar />

          </div>
        </div>
       </div>}


      </body>
    </html>
  );
}    

export default Layout;