import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps{
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({children}) => {

return(
  <html lang="en">
      <body>
       <div className="h-screen bg-black">
        <div className="container h-full mx-auto xl:px-30 max-w-6xl">
          <div className="grid grid-cols-4 h-full">
            
            <Sidebar/>
            
            <div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800">
                {children}
            </div>

          </div>
        </div>
       </div>
      </body>
    </html>
  );
}    

export default Layout;